site_name: Yuanji's Wiki
nav:
  - Home: index.md
  - Setup:
      - Android: setup/android.md
  - Selfhosted: selfhosted/index.md
  - Engineering: engineering/index.md
  - Blog: https://blog.gimo.me
theme:
  name: material
  #custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - mdx_truly_sane_lists:
      nested_indent: 2
