site_name: Yuanji's Wiki
nav:
  - Home: index.md
  - Setup:
      - setup/archlinux.md
      - setup/android.md
      - setup/neovim.md
  - Selfhosted:
      - selfhosted/providers.md
      - selfhosted/installation.md
      - selfhosted/code-server.md
      - selfhosted/postgresql.md
      - selfhosted/acme.sh.md
      - selfhosted/services.md
      - selfhosted/wireguard.md
  - Engineering:
      - engineering/index.md
      - engineering/ansible.md
      - engineering/python.md
      - engineering/jenkins.md
      - engineering/frontend.md
  - Life:
      - life/camera.md
      - life/recipe.md
  - Blog: https://blog.gimo.me
theme:
  name: material
  #custom_dir: overrides
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - mdx_truly_sane_lists:
      nested_indent: 2
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
