# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Yuanji's Wiki
copyright: Copyright © 2022 Yuanji All Rights Resarved.
repo_url: https://github.com/masakichi/wiki
edit_uri: edit/main/docs/
nav:
  - Welcome: index.md
  - Coding:
      - coding/markdown.md
      - coding/git.md
      - coding/bash.md
      - coding/go.md
      - coding/python.md
      - coding/database.md
      - "Frontend":
          - coding/frontend/index.md
          - coding/frontend/javascript.md
      - coding/vim.md
      - coding/interview.md
      - coding/gitlab.md
  - DevOps:
      - devops/ansible.md
      - devops/ssh.md
      - devops/docker.md
      - devops/jenkins.md
      - "Kubernetes":
          - devops/kubernetes/index.md
          - devops/kubernetes/kustomize.md
  - Sysadmin:
      - "Arch Linux":
          - sysadmin/archlinux/index.md
          - sysadmin/archlinux/packages.md
      - sysadmin/android.md
      - sysadmin/providers.md
      - sysadmin/installation.md
      - sysadmin/code-server.md
      - sysadmin/postgresql.md
      - sysadmin/acme.sh.md
      - sysadmin/services.md
      - sysadmin/wireguard.md
      - sysadmin/cloudflare.md
  - Toolkit: toolkit.md
  - Life:
      - life/camera.md
      - life/english.md
      - "Japan":
          - life/japan/index.md
          - life/japan/fe.md
      - life/recipe.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/masakichi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gimo_me
    - icon: fontawesome/solid/blog
      link: https://blog.gimo.me
    - icon: fontawesome/brands/telegram
      link: https://t.me/yuanji
    - icon: material/gmail
      link: mailto:self@gimo.me
theme:
  font:
    text: Cantarell
    code: Inconsolata
  name: material
  #custom_dir: overrides
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    - navigation.indexes
    - navigation.instant
    #- navigation.sections
    #- navigation.expand
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - mdx_truly_sane_lists:
      nested_indent: 2
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.betterem:
      smart_enable: all
  - abbr
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.keys
